apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- ingress.yaml
patches:
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: argocd
  target:
    kind: ClusterRoleBinding
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/1
      value: --insecure
  target:
    kind: Deployment
    name: argocd-server
- patch: |-
    - op: replace
      path: /spec/type
      value: NortPort
  target:
    kind: Service
    name: argocd-server
- path: argocd-server.yaml
